//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BlinkBackend.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BlinkMovieEntities : DbContext
    {
        public BlinkMovieEntities()
            : base("name=BlinkMovieEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Admin> Admin { get; set; }
        public virtual DbSet<BalanceRequests> BalanceRequests { get; set; }
        public virtual DbSet<Clips> Clips { get; set; }
        public virtual DbSet<DramasClips> DramasClips { get; set; }
        public virtual DbSet<Editor> Editor { get; set; }
        public virtual DbSet<Favorites> Favorites { get; set; }
        public virtual DbSet<FreeMovie> FreeMovie { get; set; }
        public virtual DbSet<Genre> Genre { get; set; }
        public virtual DbSet<GetMovie> GetMovie { get; set; }
        public virtual DbSet<History> History { get; set; }
        public virtual DbSet<Interests> Interests { get; set; }
        public virtual DbSet<Movie> Movie { get; set; }
        public virtual DbSet<Reader> Reader { get; set; }
        public virtual DbSet<ReaderRate> ReaderRate { get; set; }
        public virtual DbSet<SentProject> SentProject { get; set; }
        public virtual DbSet<SentProposals> SentProposals { get; set; }
        public virtual DbSet<Summary> Summary { get; set; }
        public virtual DbSet<Users> Users { get; set; }
        public virtual DbSet<Writer> Writer { get; set; }
    }
}
