//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BlinkBackend.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Clips
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Clips()
        {
            this.GetMovie = new HashSet<GetMovie>();
        }
    
        public int Clips_ID { get; set; }
        public Nullable<int> Writer_ID { get; set; }
        public Nullable<int> Movie_ID { get; set; }
        public Nullable<int> Sent_ID { get; set; }
        public string Title { get; set; }
        public string Url { get; set; }
        public Nullable<System.DateTime> UploadDate { get; set; }
        public string Start_time { get; set; }
        public string End_time { get; set; }
        public Nullable<bool> isCompoundClip { get; set; }
        public string Description { get; set; }
        public Nullable<int> Likes { get; set; }
    
        public virtual Movie Movie { get; set; }
        public virtual Writer Writer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GetMovie> GetMovie { get; set; }
    }
}
