//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BlinkBackend.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FreeMovie
    {
        public int FreeMovie_ID { get; set; }
        public Nullable<int> Reader_ID { get; set; }
        public Nullable<int> Movie_ID { get; set; }
        public Nullable<int> Writer_ID { get; set; }
        public Nullable<int> Episode { get; set; }
        public string issueDate { get; set; }
    }
}
