//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BlinkBackend.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GetMovie
    {
        public int GetMovie_ID { get; set; }
        public Nullable<int> Editor_ID { get; set; }
        public Nullable<int> Movie_ID { get; set; }
        public Nullable<int> Writer_ID { get; set; }
        public Nullable<int> Summary_ID { get; set; }
        public Nullable<int> Clips_ID { get; set; }
    
        public virtual Clips Clips { get; set; }
        public virtual Movie Movie { get; set; }
        public virtual Summary Summary { get; set; }
        public virtual Writer Writer { get; set; }
    }
}
