//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BlinkBackend.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReaderRate
    {
        public int ReaderRate_ID { get; set; }
        public Nullable<int> Reader_ID { get; set; }
        public Nullable<int> Writer_ID { get; set; }
        public Nullable<int> Movie_ID { get; set; }
        public Nullable<double> Writer_Rating { get; set; }
        public Nullable<double> Movie_Rating { get; set; }
    
        public virtual Movie Movie { get; set; }
        public virtual Reader Reader { get; set; }
        public virtual Writer Writer { get; set; }
    }
}
