//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BlinkBackend.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SentProject
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SentProject()
        {
            this.DramasClips = new HashSet<DramasClips>();
        }
    
        public int SentProject_ID { get; set; }
        public Nullable<int> Movie_ID { get; set; }
        public Nullable<int> Editor_ID { get; set; }
        public Nullable<int> Writer_ID { get; set; }
        public Nullable<int> SentProposal_ID { get; set; }
        public string Send_at { get; set; }
        public string Status { get; set; }
        public string EditorComment { get; set; }
        public Nullable<bool> Writer_Notification { get; set; }
        public Nullable<bool> Editor_Notification { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DramasClips> DramasClips { get; set; }
        public virtual Editor Editor { get; set; }
        public virtual Writer Writer { get; set; }
    }
}
