//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BlinkBackend.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users
    {
        public int User_ID { get; set; }
        public Nullable<int> Editor_ID { get; set; }
        public Nullable<int> Writer_ID { get; set; }
        public Nullable<int> Reader_ID { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public string Role { get; set; }
    
        public virtual Editor Editor { get; set; }
        public virtual Reader Reader { get; set; }
        public virtual Writer Writer { get; set; }
    }
}
